---
- hosts: network
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=bgp-unnumbered/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: copy frr daemons
      copy: src=bgp-unnumbered/{{ansible_hostname}}/daemons dest=/etc/frr/
    - name: copy frr conf
      copy: src=bgp-unnumbered/{{ansible_hostname}}/frr.conf dest=/etc/frr/
    - name: reload networking
      command: ifreload -a
    - name: reload frr
      service: name=frr state=restarted

- hosts: servers
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=bgp-unnumbered/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: restarts servers with their new configuration
      shell: sleep 1 && shutdown -r 0
      async: 1
      poll: 0
      ignore_errors: true
    - name: Wait for everything to come back up
      local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10
